source 'https://rubygems.org'

gem 'bcrypt'
gem 'thin'
gem 'sinatra', '~> 2.0'
gem 'mongoid', '~> 7.0'
gem 'mongoid-grid_fs'
gem 'carrierwave'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'sysrandom'